@startuml "tc-oir-02"

participant "Coordinator" as dir
participant "USS Testing instance" as uss #11E4B0
participant "D S S " as dss


[o-> dir: Starts test
activate dir

autonumber 0 1 "<b>[000]"

== Injection ==

dir -> uss: PUT /flight_plans/{flight_plan_id}
activate uss
uss -> dir: Responds { 406 Not Acceptable }
deactivate uss
dir -> dir: Validates response

== Assertions ==

dir -> dss: GET /oir/{flight_plan_id}
activate dss
dss -> dir: Responds { 404 Not Found }
deactivate dss
dir -> dir: Validates response


[o<-dir: Ends test
deactivate dir



@enduml